const ActivitiesData = [
    {
      "Activity ID": "1",
      "Type": "Nature Walk in MacRitchie Reservoir",
      "Link": "https://www.alltrails.com/parks/singapore/central/macritchie-reservoir-park",
      "Cost": 0,
      "Location": "MacRitchie Reservoir Park",
      "Location Estate": "Bukit Timah",
      "Area": "Central",
      "DateTime": "2024-05-06 9:00:00",
      "Day": "Saturday",
      "Date": "May 6th",
      "Time": "9:00 AM - 11:00 AM",
      "Description": "Enjoy a peaceful stroll through the lush greenery of MacRitchie Reservoir Park",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_1",
      "ImageHostLink": "https://nus-392633763.imgix.net/img_1.jpeg",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "2",
      "Type": "Cooking Class: Peranakan Delicacies",
      "Link": "https://www.sgcookinglessons.com/peranakan-cooking-class/",
      "Cost": 80,
      "Location": "Katong Kitchen",
      "Location Estate": "Katong",
      "Area": "East",
      "DateTime": "2024-05-07 14:00:00",
      "Day": "Sunday",
      "Date": "May 7th",
      "Time": "2:00 PM - 5:00 PM",
      "Description": "Learn how to prepare authentic Peranakan dishes from experienced chefs",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_2",
      "ImageHostLink": "https://nus-392633763.imgix.net/img_2.jpeg",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "3",
      "Type": "Yoga and Meditation Retreat",
      "Link": "https://www.eventbrite.sg/d/singapore--singapore/yoga-retreat/",
      "Cost": 120,
      "Location": "East Coast Park",
      "Location Estate": "Marine Parade",
      "Area": "East",
      "DateTime": "2024-05-13 8:00:00",
      "Day": "Saturday",
      "Date": "May 13th",
      "Time": "8:00 AM - 12:00 PM",
      "Description": "Find inner peace and rejuvenate your mind and body with yoga and meditation sessions",
      "Tags": "Fitness, Wellness",
      "Event Image": "img_3",
      "ImageHostLink": "https://nus-392633763.imgix.net/img_3.jpeg",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "4",
      "Type": "Art Jamming Workshop",
      "Link": "https://artefakts.sg/wp/book-here/",
      "Cost": 50,
      "Location": "Goodman Arts Centre",
      "Location Estate": "Mountbatten",
      "Area": "East",
      "DateTime": "2024-05-19 19:00:00",
      "Day": "Friday",
      "Date": "May 19th",
      "Time": "7:00 PM - 9:00 PM",
      "Description": "Unleash your creativity and explore different art techniques with a professional artist",
      "Tags": "Art, Workshop",
      "Event Image": "img_4",
      "ImageHostLink": "https://nus-392633763.imgix.net/img_4.jpeg",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "5",
      "Type": "Guided Tour of the National Museum",
      "Link": "https://www.googleadservices.com/pagead/aclk?sa=L&ai=DChcSEwis3M__nZaFAxW8YEECHXCuAqEYABAXGgJ3cw&ase=2&gclid=CjwKCAjwh4-wBhB3EiwAeJsppMl3S6t9RnxBdoIVhtS6ZiDU2E3g4lI8oun-b3_9jSL3smeVpFOi2xoCXwQQAvD_BwE&ohost=www.google.com&cid=CAESV-D2hAQ_1wVyN5iNhmCu2ONgUpfsFF4QX_NBY-JO1kEiayURyE5qzBJC3rh_JUM9-ZSBWefeIs_T6OPtfnawo2_-CBOLS02CeA7I9kQhWN4NNKQS-uggmQ&sig=AOD64_2tkXahGql-kBi2VsYHAWrP_keQuA&adurl=&ved=2ahUKEwjk9Mf_nZaFAxXEgf0HHd4sD4EQ4bEFegQIAxAH",
      "Cost": 15,
      "Location": "National Museum of Singapore",
      "Location Estate": "Downtown Core",
      "Area": "Central",
      "DateTime": "2024-05-20 10:00:00",
      "Day": "Saturday",
      "Date": "May 20th",
      "Time": "10:00 AM - 12:00 PM",
      "Description": "Discover Singapore's rich history and cultural heritage through interactive exhibits",
      "Tags": "History, Guided Tour",
      "Event Image": "img_5",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "6",
      "Type": "Birdwatching at Sungei Buloh Wetland Reserve",
      "Link": "https://www.alltrails.com/parks/singapore/central/sungei-buloh-wetland-reserve/birding",
      "Cost": 0,
      "Location": "Sungei Buloh Wetland Reserve",
      "Location Estate": "Lim Chu Kang",
      "Area": "North",
      "DateTime": "2024-05-21 7:00:00",
      "Day": "Sunday",
      "Date": "May 21st",
      "Time": "7:00 AM - 10:00 AM",
      "Description": "Spot various species of migratory birds in their natural habitat",
      "Tags": "Nature, Wildlife",
      "Event Image": "img_6",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "7",
      "Type": "Terrarium Building Workshop",
      "Link": "https://www.sppfy.com/products/terrarium-workshop",
      "Cost": 60,
      "Location": "Far East Flora",
      "Location Estate": "Central Water Catchment",
      "Area": "Central",
      "DateTime": "2024-05-27 14:00:00",
      "Day": "Saturday",
      "Date": "May 27th",
      "Time": "2:00 PM - 4:00 PM",
      "Description": "Create your own miniature garden in a glass container under expert guidance",
      "Tags": "Nature, Workshop",
      "Event Image": "img_7",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "8",
      "Type": "Karaoke Night",
      "Link": "https://partyworldktv.com.sg/",
      "Cost": 25,
      "Location": "Party World KTV",
      "Location Estate": "Tanglin",
      "Area": "Central",
      "DateTime": "2024-06-02 20:00:00",
      "Day": "Friday",
      "Date": "June 2nd",
      "Time": "8:00 PM - 11:00 PM",
      "Description": "Sing your heart out and have fun with friends at a lively karaoke joint",
      "Tags": "Entertainment, Social",
      "Event Image": "img_8",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "9",
      "Type": "Qi Gong and Tai Chi Class",
      "Link": "https://www.google.com/search?q=Qi+Gong+and+Tai+Chi+Class&rlz=1C5CHFA_enSG976SG976&oq=Qi+Gong+and+Tai+Chi+Class&gs_lcrp=EgZjaHJvbWUyBggAEEUYOdIBBzI1OWowajmoAgCwAgA&sourceid=chrome&ie=UTF-8#:~:text=Nam%20Wah%20Pai%3A%20Singapore,https%3A//namwahpai.sg",
      "Cost": 40,
      "Location": "Chinese Garden",
      "Location Estate": "Jurong East",
      "Area": "West",
      "DateTime": "2024-06-06 7:00:00",
      "Day": "Tuesday",
      "Date": "June 6th",
      "Time": "7:00 AM - 8:30 AM",
      "Description": "Learn ancient Chinese practices for physical and mental well-being",
      "Tags": "Fitness, Cultural",
      "Event Image": "img_9",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "10",
      "Type": "Singapore River Cruise",
      "Link": "https://rivercruise.com.sg/",
      "Cost": 25,
      "Location": "Clarke Quay",
      "Location Estate": "Downtown Core",
      "Area": "Central",
      "DateTime": "2024-06-10 19:00:00",
      "Day": "Saturday",
      "Date": "June 10th",
      "Time": "7:00 PM - 8:30 PM",
      "Description": "Enjoy stunning views of Singapore's iconic skyline from the water",
      "Tags": "Sightseeing, Guided Tour",
      "Event Image": "img_10",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Daily"
    },
    {
      "Activity ID": "11",
      "Type": "Salsa Dance Lessons",
      "Link": "https://www.caliente-dance.com/",
      "Cost": 60,
      "Location": "Dancepointe Studio",
      "Location Estate": "Jurong East",
      "Area": "West",
      "DateTime": "2024-06-15 19:30:00",
      "Day": "Thursday",
      "Date": "June 15th",
      "Time": "7:30 PM - 9:00 PM",
      "Description": "Learn the sensual and energetic moves of salsa dancing",
      "Tags": "Dance, Fitness",
      "Event Image": "img_11",
      "ImageHostLink": "https://nus-392633763.imgix.net/img_13.jpeg",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "12",
      "Type": "Kueh Appreciation Workshop",
      "Link": "https://www.klook.com/en-US/activity/22497-kueh-appreciation-day-slow-food-singapore/",
      "Cost": 50,
      "Location": "Singapore Flyer",
      "Location Estate": "Downtown Core",
      "Area": "Central",
      "DateTime": "2024-06-18 10:00:00",
      "Day": "Sunday",
      "Date": "June 18th",
      "Time": "10:00 AM - 12:00 PM",
      "Description": "Discover the history and flavors of traditional Singaporean kuehs",
      "Tags": "Food, Cultural",
      "Event Image": "img_12",
      "ImageHostLink": "https://nus-392633763.imgix.net/img_12.jpeg",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "13",
      "Type": "Gem Biscuit Workshop",
      "Link": "https://bakerybrera.com/?fbclid=IwAR38M9G98GSzMFNZmdLdRq6KBrCXiuRLcEUlmO6z2zZ3Ce0GjYZuIQJMq98_aem_AWDwBOxdauFc1az4VYDOR3xFYwPFhcJwEQCbqcR3qdFbBx_dxj0pRnFZS7-y6E85j9C_5hJoZ4BbyB3WWAuv2Oq3",
      "Cost": 45,
      "Location": "Bakery Brera",
      "Location Estate": "Tanjong Pagar",
      "Area": "Central",
      "DateTime": "2024-06-24 15:00:00",
      "Day": "Saturday",
      "Date": "June 24th",
      "Time": "3:00 PM - 5:00 PM",
      "Description": "Learn how to make delicious gem biscuits, a local favorite",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_13",
      "ImageHostLink": "https://nus-392633763.imgix.net/img_1.jpeg",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "14",
      "Type": "Batik Indigo Dyeing Workshop",
      "Link": "https://kamal.sg/2021/12/19/dyeing-adventure-batik-indigo-dyeing-workshop-malay-heritage-centre/",
      "Cost": 70,
      "Location": "Malay Heritage Centre",
      "Location Estate": "Rochor",
      "Area": "Central",
      "DateTime": "2024-06-30 18:00:00",
      "Day": "Friday",
      "Date": "June 30th",
      "Time": "6:00 PM - 8:00 PM",
      "Description": "Explore the traditional art of batik painting and create your own masterpiece",
      "Tags": "Art, Cultural",
      "Event Image": "img_14",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "15",
      "Type": "Guided Tour of Gardens by the Bay",
      "Link": "https://tribe-tours.com/product/gardens-by-the-bay-guided-tour/",
      "Cost": 20,
      "Location": "Gardens by the Bay",
      "Location Estate": "Marina East",
      "Area": "Central",
      "DateTime": "2024-07-01 9:00:00",
      "Day": "Saturday",
      "Date": "July 1st",
      "Time": "9:00 AM - 11:00 AM",
      "Description": "Explore the stunning landscapes and futuristic conservatories of this iconic attraction",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_15",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Daily"
    },
    {
      "Activity ID": "16",
      "Type": "Pottery Making Workshop",
      "Link": "https://www.potteryjungle.com/workshop",
      "Cost": 80,
      "Location": "Thow Kwang Pottery Jungle",
      "Location Estate": "Pioneer",
      "Area": "West",
      "DateTime": "2024-07-09 14:00:00",
      "Day": "Sunday",
      "Date": "July 9th",
      "Time": "2:00 PM - 4:30 PM",
      "Description": "Learn the art of pottery making and create your own ceramic pieces",
      "Tags": "Art, Workshop",
      "Event Image": "img_16",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "17",
      "Type": "Peranakan Museum Visit",
      "Link": "https://www.nhb.gov.sg/peranakanmuseum/",
      "Cost": 10,
      "Location": "Peranakan Museum",
      "Location Estate": "Downtown Core",
      "Area": "Central",
      "DateTime": "2024-07-14 10:00:00",
      "Day": "Friday",
      "Date": "July 14th",
      "Time": "10:00 AM - 12:00 PM",
      "Description": "Immerse yourself in the rich cultural heritage of the Peranakan community",
      "Tags": "History, Cultural",
      "Event Image": "img_17",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "18",
      "Type": "Terrarium Building Workshop",
      "Link": "https://www.kkday.com/en-sg/product/103429-open-terrarium-workshop-funan-singapore",
      "Cost": 44,
      "Location": "KKDay",
      "Location Estate": "Central Water Catchment",
      "Area": "Central",
      "DateTime": "2024-07-15 14:00:00",
      "Day": "Saturday",
      "Date": "July 15th",
      "Time": "2:00 PM - 4:00 PM",
      "Description": "Create your own miniature garden in a glass container under expert guidance",
      "Tags": "Nature, Workshop",
      "Event Image": "img_18",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "19",
      "Type": "Guided Tour of Chinatown",
      "Link": "https://chinatown.sg/explore/",
      "Cost": 15,
      "Location": "Chinatown",
      "Location Estate": "Outram",
      "Area": "Central",
      "DateTime": "2024-07-16 11:00:00",
      "Day": "Sunday",
      "Date": "July 16th",
      "Time": "11:00 AM - 1:00 PM",
      "Description": "Explore the vibrant sights, sounds, and flavors of Singapore's Chinatown",
      "Tags": "Cultural, Guided Tour",
      "Event Image": "img_19",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "20",
      "Type": "Baking Class: Traditional Nyonya Kueh",
      "Link": "https://www.bakefresh.com.sg/workshops/mastering-nyonya-kueh/",
      "Cost": 240,
      "Location": "BakeFresh",
      "Location Estate": "Tanjong Pagar",
      "Area": "Central",
      "DateTime": "2024-07-22 10:00:00",
      "Day": "Saturday",
      "Date": "July 22nd",
      "Time": "10:00 AM - 12:30 PM",
      "Description": "Learn how to make authentic Nyonya kuehs from experienced bakers",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_20",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "21",
      "Type": "Guided Nature Walk in Bukit Timah Nature Reserve",
      "Link": "https://www.alltrails.com/en-gb/parks/singapore/central/bukit-timah-nature-reserve",
      "Cost": 0,
      "Location": "Bukit Timah Nature Reserve",
      "Location Estate": "Bukit Timah",
      "Area": "Central",
      "DateTime": "2024-07-23 8:00:00",
      "Day": "Sunday",
      "Date": "July 23rd",
      "Time": "8:00 AM - 10:30 AM",
      "Description": "Explore the lush rainforest and discover local flora and fauna",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_21",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "22",
      "Type": "Ukulele Lessons for Beginners",
      "Link": "https://www.replugged.com/",
      "Cost": 50,
      "Location": "Replugged Music School",
      "Location Estate": "Bugis",
      "Area": "Central",
      "DateTime": "2024-07-26 19:00:00",
      "Day": "Wednesday",
      "Date": "July 26th",
      "Time": "7:00 PM - 8:30 PM",
      "Description": "Learn how to play the ukulele and enjoy the joy of music",
      "Tags": "Music, Workshop",
      "Event Image": "img_22",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "23",
      "Type": "Guided Tour of Singapore Flyer",
      "Link": "https://www.singaporeflyer.com/",
      "Cost": 33,
      "Location": "Singapore Flyer",
      "Location Estate": "Downtown Core",
      "Area": "Central",
      "DateTime": "2024-07-28 19:00:00",
      "Day": "Friday",
      "Date": "July 28th",
      "Time": "7:00 PM - 8:30 PM",
      "Description": "Enjoy stunning views of Singapore's skyline from the iconic Singapore Flyer",
      "Tags": "Sightseeing, Guided Tour",
      "Event Image": "img_23",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Daily"
    },
    {
      "Activity ID": "24",
      "Type": "Terrarium Building Workshop",
      "Link": "https://www.google.com/search?q=Terrarium+Building+Workshop&rlz=1C5CHFA_enSG976SG976&oq=Terrarium+Building+Workshop&gs_lcrp=EgZjaHJvbWUqBggAEEUYOzIGCAAQRRg7MgYIARBFGDsyBggCEEUYOzIGCAMQRRg70gEHMzQwajBqOagCALACAA&sourceid=chrome&ie=UTF-8#:~:text=Terrarium%20Workshop,%E2%80%BA%20workshops%20%E2%80%BA%20terrarium%2D...",
      "Cost": 50,
      "Location": "InOut Atelier",
      "Location Estate": "Rochor",
      "Area": "Central",
      "DateTime": "2024-08-05 14:00:00",
      "Day": "Saturday",
      "Date": "August 5th",
      "Time": "2:00 PM - 4:00 PM",
      "Description": "Create your own miniature garden in a glass container under expert guidance",
      "Tags": "Nature, Workshop",
      "Event Image": "img_24",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "25",
      "Type": "Aqua Aerobics Class",
      "Link": "https://www.sportshub.com.sg/sport-fitness/swimming/aqua-fitness-classes",
      "Cost": 40,
      "Location": "Kallang Wave Mall",
      "Location Estate": "Kallang",
      "Area": "Central",
      "DateTime": "2024-08-08 9:00:00",
      "Day": "Tuesday",
      "Date": "August 8th",
      "Time": "9:00 AM - 10:30 AM",
      "Description": "Stay fit and have fun with low-impact aqua aerobics exercises",
      "Tags": "Fitness, Water Sports",
      "Event Image": "img_25",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "26",
      "Type": "Singapore Art Museum Visit",
      "Link": "https://www.visitsingapore.com/see-do-singapore/arts/museums-galleries/singapore-art-museum/",
      "Cost": 15,
      "Location": "Singapore Art Museum",
      "Location Estate": "Downtown Core",
      "Area": "Central",
      "DateTime": "2024-08-12 14:00:00",
      "Day": "Saturday",
      "Date": "August 12th",
      "Time": "2:00 PM - 4:00 PM",
      "Description": "Explore the rich and diverse works of local and international artists",
      "Tags": "Art, Cultural",
      "Event Image": "img_26",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Daily"
    },
    {
      "Activity ID": "27",
      "Type": "Guided Tour of Haw Par Villa",
      "Link": "https://www.hawparvilla.sg/tours-trails/",
      "Cost": 12,
      "Location": "Haw Par Villa",
      "Location Estate": "Queenstown",
      "Area": "Central",
      "DateTime": "2024-08-13 10:00:00",
      "Day": "Sunday",
      "Date": "August 13th",
      "Time": "10:00 AM - 12:00 PM",
      "Description": "Discover the unique and eccentric world of Haw Par Villa",
      "Tags": "Cultural, Guided Tour",
      "Event Image": "img_27",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "28",
      "Type": "Studio Workshop – Terrarium Making",
      "Link": "https://epicworkshops.com.sg/product/studio-workshop-terrarium/",
      "Cost": 46,
      "Location": "Epicworkshops",
      "Location Estate": "Central Water Catchment",
      "Area": "Central",
      "DateTime": "2024-08-19 14:00:00",
      "Day": "Saturday",
      "Date": "August 19th",
      "Time": "2:00 PM - 4:00 PM",
      "Description": "Create your own miniature garden in a glass container under expert guidance",
      "Tags": "Nature, Workshop",
      "Event Image": "img_28",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "29",
      "Type": "Batik Painting Class",
      "Link": "https://www.culturally.co/workshops/get-creative-with-batik-singapore",
      "Cost": 90,
      "Location": "culturally.co",
      "Location Estate": "Paya Lebar",
      "Area": "East",
      "DateTime": "2024-08-25 18:00:00",
      "Day": "Friday",
      "Date": "August 25th",
      "Time": "6:00 PM - 8:00 PM",
      "Description": "Explore the traditional art of batik painting and create your own masterpiece",
      "Tags": "Art, Cultural",
      "Event Image": "img_29",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "30",
      "Type": "Guided Tour of Sentosa Island",
      "Link": "https://www.headout.com/singapore-sentosa-attractions-tickets/sentosa-island-guided-bus-tour-e-13593/?utm_source=google&utm_medium=ttd&utm_term=13593&product-id=13593&option_id=25912&source=e&language=en-SG&currency=SGD",
      "Cost": 19,
      "Location": "Sentosa Island",
      "Location Estate": "Sentosa",
      "Area": "Central",
      "DateTime": "2024-08-26 10:00:00",
      "Day": "Saturday",
      "Date": "August 26th",
      "Time": "10:00 AM - 12:30 PM",
      "Description": "Explore the beaches, attractions, and natural beauty of Sentosa Island",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_30",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Daily"
    },
    {
      "Activity ID": "31",
      "Type": "Cooking Class: Authentic Teochew Cuisine",
      "Link": "https://artzbakingculinary.com/",
      "Cost": 90,
      "Location": "Cooking Studio",
      "Location Estate": "Lavender",
      "Area": "East",
      "DateTime": "2024-05-12 14:00:00",
      
      "Description": "Learn to prepare traditional Teochew dishes from experienced chefs",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_31",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "32",
      "Type": "Guided Nature Walk in Sungei Buloh Wetland Reserve",
      "Link": "https://www.sassymamasg.com/sungei-buloh-wetland-reserve-nature-birds-crocodiles/",
      "Cost": 0,
      "Location": "Sungei Buloh Wetland Reserve",
      "Location Estate": "Sungei Buloh",
      "Area": "North",
      "DateTime": "2024-05-19 8:00:00",
      
      "Description": "Explore the rich biodiversity of the wetland reserve with a knowledgeable guide",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_32",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "33",
      "Type": "Qi Gong and Tai Chi Class",
      "Link": "https://singaporeccc.org.sg/events/taiji-qigong-classes/",
      "Cost": 45,
      "Location": "Chinese Garden",
      "Location Estate": "Chinese Garden",
      "Area": "West",
      "DateTime": "2024-05-26 7:30:00",
      
      "Description": "Improve physical and mental well-being through ancient Chinese practices",
      "Tags": "Fitness, Cultural",
      "Event Image": "img_33",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "34",
      "Type": "Traditional Kite Making Workshop",
      "Link": "https://www.kiteculture.sg/",
      "Cost": 55,
      "Location": "Marina Barrage",
      "Location Estate": "Marina Barrage",
      "Area": "Central",
      "DateTime": "2024-06-02 15:00:00",
      
      "Description": "Learn the art of making traditional kites and take home your creation",
      "Tags": "Cultural, Workshop",
      "Event Image": "img_34",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "35",
      "Type": "Guided Tour of Kampong Glam",
      "Link": "https://www.monsterdaytours.com/singapore-free-walking-tours/kampong-gelam-walking-tour",
      "Cost": 18,
      "Location": "Kampong Glam Heritage Trail",
      "Location Estate": "Kampong Glam",
      "Area": "Central",
      "DateTime": "2024-06-09 10:00:00",
      
      "Description": "Discover the rich cultural heritage of the Malay community in this historic district",
      "Tags": "Cultural, Guided Tour",
      "Event Image": "img_35",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "36",
      "Type": "Calligraphy Class",
      "Link": "https://www.leahdesign.sg/",
      "Cost": 65,
      "Location": "Woodlands Community Club",
      "Location Estate": "Woodlands",
      "Area": "North",
      "DateTime": "2024-06-16 13:00:00",
      
      "Description": "Learn the art of Chinese calligraphy and create beautiful works of art",
      "Tags": "Art, Cultural",
      "Event Image": "img_36",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "37",
      "Type": "Guided Tour of Pulau Ubin",
      "Link": "https://www.letsgotoursingapore.com/tours/pulau-ubin-tour/",
      "Cost": 20,
      "Location": "Changi Point Ferry Terminal",
      "Location Estate": "Changi Point Ferry Terminal",
      "Area": "East",
      "DateTime": "2024-06-23 9:00:00",
      
      "Description": "Explore the rustic charm of Pulau Ubin and learn about its rich history",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_37",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "38",
      "Type": "Baking Class: Traditional Kueh Lapis",
      "Link": "https://www.bakersbrew.com/class/bakers-brew-baking-classes-in-singapore/heritage-series/artisanal-kueh-masterclass",
      "Cost": 75,
      "Location": "Ang Mo Kio Community Centre",
      "Location Estate": "Ang Mo Kio",
      "Area": "North-East",
      "DateTime": "2024-06-30 11:00:00",
      
      "Description": "Master the art of making the iconic multi-layered Kueh Lapis cake",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_38",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "39",
      "Type": "Guided Tour of Fort Canning Park",
      "Link": "https://beta.nparks.gov.sg/visit/parks/fort-canning-park/activities/heritage-walks-tours",
      "Cost": 12,
      "Location": "Fort Canning Park",
      "Location Estate": "Fort Canning Park",
      "Area": "Central",
      "DateTime": "2024-07-07 15:00:00",
      
      "Description": "Uncover the rich history and heritage of this iconic park",
      "Tags": "History, Guided Tour",
      "Event Image": "img_39",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "40",
      "Type": "Traditional Hakka Embroidery Workshop",
      "Link": "https://mysticgardens.com.sg/product/embroidery-workshop/",
      "Cost": 60,
      "Location": "Yishun Community Club",
      "Location Estate": "Yishun",
      "Area": "North",
      "DateTime": "2024-07-14 14:00:00",
      
      "Description": "Learn the intricate art of Hakka embroidery and create beautiful pieces",
      "Tags": "Art, Cultural",
      "Event Image": "img_40",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "41",
      "Type": "Guided Tour of Kranji Countryside",
      "Link": "https://www.klook.com/en-SG/activity/53040-kranji-countryside-tour/",
      "Cost": 25,
      "Location": "Kranji Countryside",
      "Location Estate": "Kranji",
      "Area": "North",
      "DateTime": "2024-07-21 8:30:00",
      
      "Description": "Explore the rustic charm of Singapore's countryside and learn about its farming heritage",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_41",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "42",
      "Type": "Cooking Class: Authentic Eurasian Cuisine",
      "Link": "https://google.com",
      "Cost": 85,
      "Location": "Katong Kitchen",
      "Location Estate": "Katong",
      "Area": "East",
      "DateTime": "2024-07-28 16:00:00",
      
      "Description": "Learn to prepare traditional Eurasian dishes from experienced chefs",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_42",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "43",
      "Type": "Guided Tour of Jurong Lake Gardens",
      "Link": "https://google.com",
      "Cost": 0,
      "Location": "Jurong Lake Gardens",
      "Location Estate": "Jurong Lake Gardens",
      "Area": "West",
      "DateTime": "2024-08-04 10:00:00",
      
      "Description": "Discover the natural beauty and diverse flora and fauna of this urban park",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_43",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "44",
      "Type": "Traditional Chinese Brush Painting Class",
      "Link": "https://google.com",
      "Cost": 70,
      "Location": "Bishan Community Club",
      "Location Estate": "Bishan",
      "Area": "Central",
      "DateTime": "2024-08-11 13:30:00",
      
      "Description": "Learn the art of Chinese brush painting and create beautiful landscapes",
      "Tags": "Art, Cultural",
      "Event Image": "img_44",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "45",
      "Type": "Guided Tour of Singapore Botanic Gardens",
      "Link": "https://google.com",
      "Cost": 15,
      "Location": "Singapore Botanic Gardens",
      "Location Estate": "Singapore Botanic Gardens",
      "Area": "Central",
      "DateTime": "2024-08-18 9:00:00",
      
      "Description": "Explore the stunning gardens and learn about the rich plant diversity",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_45",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Daily"
    },
    {
      "Activity ID": "46",
      "Type": "Baking Class: Traditional Nonya Kueh",
      "Link": "https://google.com",
      "Cost": 80,
      "Location": "Joo Chiat Culinary School",
      "Location Estate": "Joo Chiat",
      "Area": "East",
      "DateTime": "2024-08-25 14:00:00",
      
      "Description": "Learn how to make authentic Nonya kuehs from experienced bakers",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_46",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "47",
      "Type": "Guided Tour of Changi Museum",
      "Link": "https://google.com",
      "Cost": 10,
      "Location": "Changi Museum",
      "Location Estate": "Changi Museum",
      "Area": "East",
      "DateTime": "2024-09-01 11:00:00",
      
      "Description": "Learn about the harsh conditions faced by prisoners of war during World War II",
      "Tags": "History, Guided Tour",
      "Event Image": "img_47",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Daily"
    },
    {
      "Activity ID": "48",
      "Type": "Traditional Batik Painting Workshop",
      "Link": "https://google.com",
      "Cost": 75,
      "Location": "Geylang Serai Malay Village",
      "Location Estate": "Geylang",
      "Area": "East",
      "DateTime": "2024-09-08 15:00:00",
      
      "Description": "Explore the art of batik painting and create your own masterpiece",
      "Tags": "Art, Cultural",
      "Event Image": "img_48",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "49",
      "Type": "Guided Nature Walk in Bukit Batok Nature Park",
      "Link": "https://google.com",
      "Cost": 0,
      "Location": "Bukit Batok Nature Park",
      "Location Estate": "Bukit Batok Nature Park",
      "Area": "West",
      "DateTime": "2024-09-15 8:30:00",
      
      "Description": "Explore the rich biodiversity of this urban nature park",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_49",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "50",
      "Type": "Traditional Rattan Weaving Workshop",
      "Link": "https://google.com",
      "Cost": 60,
      "Location": "Woodlands Galaxy Community Centre",
      "Location Estate": "Woodlands",
      "Area": "North",
      "DateTime": "2024-09-22 14:00:00",
      
      "Description": "Learn the art of rattan weaving and create beautiful baskets and furniture",
      "Tags": "Art, Cultural",
      "Event Image": "img_50",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "51",
      "Type": "Guided Tour of Tiong Bahru Estate",
      "Link": "https://google.com",
      "Cost": 18,
      "Location": "Tiong Bahru Estate",
      "Location Estate": "Tiong Bahru",
      "Area": "Central",
      "DateTime": "2024-09-29 10:00:00",
      
      "Description": "Discover the rich architectural heritage and local culture of this iconic estate",
      "Tags": "Culture, Guided Tour",
      "Event Image": "img_51",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "52",
      "Type": "Cooking Class: Authentic Peranakan Cuisine",
      "Link": "https://google.com",
      "Cost": 95,
      "Location": "Katong Kitchen",
      "Location Estate": "Joo Chiat",
      "Area": "East",
      "DateTime": "2024-10-06 16:00:00",
      
      "Description": "Learn to prepare traditional Peranakan dishes from experienced chefs",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_52",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "One-off"
    },
    {
      "Activity ID": "53",
      "Type": "Guided Tour of Seletar Aerospace Park",
      "Link": "https://google.com",
      "Cost": 20,
      "Location": "Seletar Aerospace Park",
      "Location Estate": "Seletar",
      "Area": "North",
      "DateTime": "2024-10-13 9:30:00",
      
      "Description": "Explore the history and development of Singapore's aviation industry",
      "Tags": "History, Guided Tour",
      "Event Image": "img_53",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "54",
      "Type": "Traditional Beading Workshop",
      "Link": "https://google.com",
      "Cost": 65,
      "Location": "Ang Mo Kio Community Centre",
      "Location Estate": "Ang Mo Kio",
      "Area": "North-East",
      "DateTime": "2024-10-20 13:00:00",
      
      "Description": "Learn the art of beading and create beautiful jewelry and accessories",
      "Tags": "Art, Cultural",
      "Event Image": "img_54",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "55",
      "Type": "Guided Tour of Bukit Brown Cemetery",
      "Link": "https://google.com",
      "Cost": 15,
      "Location": "Bukit Brown Cemetery",
      "Location Estate": "Bukit Brown",
      "Area": "Central",
      "DateTime": "2024-10-27 10:00:00",
      
      "Description": "Discover the rich history and heritage of this iconic cemetery",
      "Tags": "History, Guided Tour",
      "Event Image": "img_55",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "56",
      "Type": "Baking Class: Traditional Eurasian Sugee Cake",
      "Link": "https://google.com",
      "Cost": 70,
      "Location": "Katong Baking Studio",
      "Location Estate": "Katong",
      "Area": "East",
      "DateTime": "2024-11-03 14:00:00",
      
      "Description": "Learn how to make the iconic Eurasian Sugee Cake from experienced bakers",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_56",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "57",
      "Type": "Guided Tour of Sembawang Hot Spring Park",
      "Link": "https://google.com",
      "Cost": 12,
      "Location": "Sembawang Hot Spring Park",
      "Location Estate": "Sembawang",
      "Area": "North",
      "DateTime": "2024-11-10 9:00:00",
      
      "Description": "Explore the natural hot springs and learn about their history and significance",
      "Tags": "Nature, Guided Tour",
      "Event Image": "img_57",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "58",
      "Type": "Traditional Chinese Paper Cutting Workshop",
      "Link": "https://google.com",
      "Cost": 55,
      "Location": "Bishan Community Club",
      "Location Estate": "Bishan",
      "Area": "Central",
      "DateTime": "2024-11-17 15:00:00",
      
      "Description": "Learn the art of Chinese paper cutting and create beautiful designs",
      "Tags": "Art, Cultural",
      "Event Image": "img_58",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Monthly"
    },
    {
      "Activity ID": "59",
      "Type": "Guided Tour of Gillman Barracks",
      "Link": "https://google.com",
      "Cost": 18,
      "Location": "Gillman Barracks",
      "Location Estate": "Gillman Barracks",
      "Area": "Central",
      "DateTime": "2024-11-24 11:00:00",
      
      "Description": "Discover the rich art scene and explore the contemporary art galleries",
      "Tags": "Art, Guided Tour",
      "Event Image": "img_59",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "Weekly"
    },
    {
      "Activity ID": "60",
      "Type": "Cooking Class: Authentic Hakka Cuisine",
      "Link": "https://google.com",
      "Cost": 90,
      "Location": "Yishun Culinary Institute",
      "Location Estate": "Yishun",
      "Area": "North",
      "DateTime": "2024-12-01 16:00:00",
      
      "Description": "Learn to prepare traditional Hakka dishes from experienced chefs",
      "Tags": "Cooking, Cultural",
      "Event Image": "img_60",
      "ImageHostLink": "",
      "hasHappened": 0,
      "Frequency": "One-off"
    }
  ]

export default ActivitiesData;