const SampleData = [
    {
        "Activity ID": "1",
        "Type": "Nature Walk in MacRitchie Reservoir",
        "Cost": "0",
        "Location": "MacRitchie Reservoir Park",
        "Location Estate": "Bukit Timah",
        "DateTime ": "2024-05-06 9:00:00",
        "Day": "Saturday",
        "Date": "May 6th",
        "Time": "9:00 AM - 11:00 AM",
        "Description": "Enjoy a peaceful stroll through the lush greenery of MacRitchie Reservoir Park",
        "Rating": "5",
        "Tags": "Nature, Guided Tour",
        "Image": ""
    },
    {
        "Activity ID": "2",
        "Type": "Cooking Class: Peranakan Delicacies",
        "Cost": "80",
        "Location": "Katong Kitchen",
        "Location Estate": "Katong",
        "DateTime ": "2024-05-07 14:00:00",
        "Day": "Sunday",
        "Date": "May 7th",
        "Time": "2:00 PM - 5:00 PM",
        "Description": "Learn how to prepare authentic Peranakan dishes from experienced chefs",
        "Rating": "4.4",
        "Tags": "Cooking, Cultural",
        "Image": "Activity.png"
    },
    {
        "Activity ID": "3",
        "Type": "Yoga and Meditation Retreat",
        "Cost": "120",
        "Location": "East Coast Park",
        "Location Estate": "Marine Parade",
        "DateTime ": "2024-05-13 8:00:00",
        "Day": "Saturday",
        "Date": "May 13th",
        "Time": "8:00 AM - 12:00 PM",
        "Description": "Find inner peace and rejuvenate your mind and body with yoga and meditation sessions",
        "Rating": "4",
        "Tags": "Fitness, Wellness",
        "Image": ""
    },
    {
        "Activity ID": "4",
        "Type": "Art Jamming Workshop",
        "Cost": "50",
        "Location": "Goodman Arts Centre",
        "Location Estate": "Mountbatten",
        "DateTime ": "2024-05-19 19:00:00",
        "Day": "Friday",
        "Date": "May 19th",
        "Time": "7:00 PM - 9:00 PM",
        "Description": "Unleash your creativity and explore different art techniques with a professional artist",
        "Rating": "4.7",
        "Tags": "Art, Workshop",
        "Image": ""
    },
    {
        "Activity ID": "5",
        "Type": "Guided Tour of the National Museum",
        "Cost": "15",
        "Location": "National Museum of Singapore",
        "Location Estate": "Downtown Core",
        "DateTime ": "2024-05-20 10:00:00",
        "Day": "Saturday",
        "Date": "May 20th",
        "Time": "10:00 AM - 12:00 PM",
        "Description": "Discover Singapore's rich history and cultural heritage through interactive exhibits",
        "Rating": "4.9",
        "Tags": "History, Guided Tour",
        "Image": ""
    },
    {
        "Activity ID": "6",
        "Type": "Birdwatching at Sungei Buloh Wetland Reserve",
        "Cost": "0",
        "Location": "Sungei Buloh Wetland Reserve",
        "Location Estate": "Lim Chu Kang",
        "DateTime ": "2024-05-21 7:00:00",
        "Day": "Sunday",
        "Date": "May 21st",
        "Time": "7:00 AM - 10:00 AM",
        "Description": "Spot various species of migratory birds in their natural habitat",
        "Rating": "4.5",
        "Tags": "Nature, Wildlife",
        "Image": "/bt3103-images/Copy of macritche.png"
    }
  ]

  export default SampleData;